#!/bin/bash

if [ -d bats ]; then
  ( 
    cd bats
    echo Updating bats:
    git pull
  )
else
  git clone https://github.com/sstephenson/bats.git 
fi

if [ -d phpenv ]; then
  ( 
    cd phpenv
    echo Updating phpenv:
    git pull
  )
else
  git clone https://github.com/madumlao/phpenv.git
fi

